# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorID', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('AuthorID', models.IntegerField()),
                ('Publisher', models.CharField(max_length=50)),
                ('PublishDate', models.DateField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
