# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='author',
            name='Age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='Country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='Name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
