# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0002_auto_20161013_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='AuthorID',
            field=models.IntegerField(blank=True),
        ),
    ]
