# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManage', '0004_auto_20161013_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
